project:
  type: website

website:
  title: "DACSS 601: Data Science Fundamentals"
  site-url: index.qmd
  twitter-card:
    creator: "@UMassDACSS"
    site: "@UMassDACSS"
    
  favicon: images/DACSS_Round_Network.png
  navbar:
    background: "#881c1c"
    logo: images/UMass White Wordmark Horiz.png
    right:
      - text: Home
        href: index.qmd
      # - text: "Winter 2022-23 Posts"
      #   href: posts.qmd
      # - text: "Contributors"
      #   file: about.qmd
      - href: https://umass.edu/sbs/dacss
        text: "DACSS"
      - icon: github
        href: https://github.com/DACSS
        aria-label: GitHub
  page-navigation: true
execution:
  freeze: auto


format:
  html:
    smooth-scroll: true
    page-layout: full
    mainfont: Open Sans
    linkcolor: "#881c1c"
    toc: true
    theme: 
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]
    
